In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [41]:
df = pd.read_csv("Airline_customer_satisfaction.csv")
df.head()

satisfaction   Customer Type  Age   Type of Travel     Class  \
0    satisfied  Loyal Customer   65  Personal Travel       Eco   
1    satisfied  Loyal Customer   47  Personal Travel  Business   
2    satisfied  Loyal Customer   15  Personal Travel       Eco   
3    satisfied  Loyal Customer   60  Personal Travel       Eco   
4    satisfied  Loyal Customer   70  Personal Travel       Eco   

   Flight Distance  Seat comfort  Departure/Arrival time convenient  \
0              265             0                                  0   
1             2464             0                                  0   
2             2138             0                                  0   
3              623             0                                  0   
4              354             0                                  0   

   Food and drink  Gate location  ...  Online support  Ease of Online booking  \
0               0              2  ...               2                       3   
1               0              3  ...               2                       3   
2               0              3  ...               2                       2   
3               0              3  ...               3                       1   
4               0              3  ...               4                       2   

   On-board service  Leg room service  Baggage handling  Checkin service  \
0                 3                 0                 3                5   
1                 4                 4                 4                2   
2                 3                 3                 4                4   
3                 1                 0                 1                4   
4                 2                 0                 2                4   

   Cleanliness  Online boarding  Departure Delay in Minutes  \
0            3                2                           0   
1            3                2                         310   
2            4                2                           0   
3            1                3                           0   
4            2                5                           0   

   Arrival Delay in Minutes  
0                       0.0  
1                     305.0  
2                       0.0  
3                       0.0  
4                       0.0  

[5 rows x 22 columns]

In [42]:
df["Customer Type"].unique()

array(['Loyal Customer', 'disloyal Customer'], dtype=object)

In [43]:
df["Type of Travel"].unique()

array(['Personal Travel', 'Business travel'], dtype=object)

In [44]:
df["Class"].unique()

array(['Eco', 'Business', 'Eco Plus'], dtype=object)

In [46]:
df.describe()

Age  Flight Distance   Seat comfort  \
count  129880.000000    129880.000000  129880.000000   
mean       39.427957      1981.409055       2.838597   
std        15.119360      1027.115606       1.392983   
min         7.000000        50.000000       0.000000   
25%        27.000000      1359.000000       2.000000   
50%        40.000000      1925.000000       3.000000   
75%        51.000000      2544.000000       4.000000   
max        85.000000      6951.000000       5.000000   

       Departure/Arrival time convenient  Food and drink  Gate location  \
count                      129880.000000   129880.000000  129880.000000   
mean                            2.990645        2.851994       2.990422   
std                             1.527224        1.443729       1.305970   
min                             0.000000        0.000000       0.000000   
25%                             2.000000        2.000000       2.000000   
50%                             3.000000        3.000000       3.000000   
75%                             4.000000        4.000000       4.000000   
max                             5.000000        5.000000       5.000000   

       Inflight wifi service  Inflight entertainment  Online support  \
count          129880.000000           129880.000000   129880.000000   
mean                3.249130                3.383477        3.519703   
std                 1.318818                1.346059        1.306511   
min                 0.000000                0.000000        0.000000   
25%                 2.000000                2.000000        3.000000   
50%                 3.000000                4.000000        4.000000   
75%                 4.000000                4.000000        5.000000   
max                 5.000000                5.000000        5.000000   

       Ease of Online booking  On-board service  Leg room service  \
count           129880.000000     129880.000000     129880.000000   
mean                 3.472105          3.465075          3.485902   
std                  1.305560          1.270836          1.292226   
min                  0.000000          0.000000          0.000000   
25%                  2.000000          3.000000          2.000000   
50%                  4.000000          4.000000          4.000000   
75%                  5.000000          4.000000          5.000000   
max                  5.000000          5.000000          5.000000   

       Baggage handling  Checkin service    Cleanliness  Online boarding  \
count     129880.000000    129880.000000  129880.000000    129880.000000   
mean           3.695673         3.340807       3.705759         3.352587   
std            1.156483         1.260582       1.151774         1.298715   
min            1.000000         0.000000       0.000000         0.000000   
25%            3.000000         3.000000       3.000000         2.000000   
50%            4.000000         3.000000       4.000000         4.000000   
75%            5.000000         4.000000       5.000000         4.000000   
max            5.000000         5.000000       5.000000         5.000000   

       Departure Delay in Minutes  Arrival Delay in Minutes  
count               129880.000000             129487.000000  
mean                    14.713713                 15.091129  
std                     38.071126                 38.465650  
min                      0.000000                  0.000000  
25%                      0.000000                  0.000000  
50%                      0.000000                  0.000000  
75%                     12.000000                 13.000000  
max                   1592.000000               1584.000000

In [57]:
x= np.array(df.iloc[:,1:])
y= np.array(df.iloc[:,1])

In [58]:
x[0]

array(['Loyal Customer', 65, 'Personal Travel', 'Eco', 265, 0, 0, 0, 2, 2,
       4, 2, 3, 3, 0, 3, 5, 3, 2, 0, 0.0], dtype=object)

Preprocessing the Data

In [59]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()
x[:,0]=le1.fit_transform(x[:,0])
x[:,2]=le2.fit_transform(x[:,2])
x[:,3]=le3.fit_transform(x[:,3])

In [60]:
x[0]

array([0, 65, 1, 1, 265, 0, 0, 0, 2, 2, 4, 2, 3, 3, 0, 3, 5, 3, 2, 0, 0.0],
      dtype=object)

In [61]:
ley = LabelEncoder()
y = ley.fit_transform(y)

In [62]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [63]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy="mean")
imputer.fit(x[:,:])
x[:,:]=imputer.transform(x[:,:])

In [65]:
x

array([[0.0, 65.0, 1.0, ..., 2.0, 0.0, 0.0],
       [0.0, 47.0, 1.0, ..., 2.0, 310.0, 305.0],
       [0.0, 15.0, 1.0, ..., 2.0, 0.0, 0.0],
       ...,
       [1.0, 69.0, 1.0, ..., 2.0, 155.0, 163.0],
       [1.0, 66.0, 1.0, ..., 2.0, 193.0, 205.0],
       [1.0, 38.0, 1.0, ..., 3.0, 185.0, 186.0]], dtype=object)

In [66]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x[:,(1,4)]=sc.fit_transform(x[:,(1,4)])

In [67]:
x[0]

array([0.0, 1.6913508213371766, 1.0, 1.0, -1.6711027004576011, 0.0, 0.0,
       0.0, 2.0, 2.0, 4.0, 2.0, 3.0, 3.0, 0.0, 3.0, 5.0, 3.0, 2.0, 0.0,
       0.0], dtype=object)

Dividing the data into train and test set

In [68]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

In [69]:
x_train

array([[0.0, 1.2945070979208018, 0.0, ..., 4.0, 0.0, 0.0],
       [0.0, 1.3606477184901977, 1.0, ..., 3.0, 0.0, 0.0],
       [0.0, 0.5008196510880525, 0.0, ..., 2.0, 9.0, 22.0],
       ...,
       [0.0, 1.0960852362126146, 0.0, ..., 3.0, 0.0, 0.0],
       [0.0, 0.3023977893798651, 0.0, ..., 1.0, 0.0, 0.0],
       [0.0, 1.3606477184901977, 0.0, ..., 5.0, 8.0, 11.0]], dtype=object)

Applying model to training set

In [70]:
from sklearn.linear_model import LogisticRegression
logr=LogisticRegression()
logr.fit(x_train,y_train)

c:\Users\adity\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

Checking the Accuracy of the model

In [71]:
y_pred = logr.predict(x_test)

In [72]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,y_pred)

In [73]:
acc

1.0